# Generated by Django 4.0.4 on 2022-06-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagazapp', '0003_alter_lake_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='warning',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Warning and description'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude (meters)'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Area (square kilometers)'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude (decimal degrees)'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude (decimal degrees)'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Water Volume (millions of cubic meters)'),
        ),
        migrations.AlterField(
            model_name='lakemeasurement',
            name='atmospheric_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Atmospheric Pressure (hPa)'),
        ),
        migrations.AlterField(
            model_name='lakemeasurement',
            name='atmospheric_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Atmospheric Temperature (Celsius)'),
        ),
        migrations.AlterField(
            model_name='lakemeasurement',
            name='precipitation',
            field=models.FloatField(blank=True, null=True, verbose_name='Precipitation (milimeters)'),
        ),
        migrations.AlterField(
            model_name='lakemeasurement',
            name='water_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Water Level (meters)'),
        ),
        migrations.AlterField(
            model_name='lakemeasurement',
            name='water_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Water Temperature (Celsius'),
        ),
    ]
