# Generated by Django 4.0.4 on 2022-07-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagazapp', '0004_lake_warning_alter_lake_altitude_alter_lake_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lake_images'),
        ),
    ]
