# Generated by Django 4.0.4 on 2022-09-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagazapp', '0005_lake_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='station_status',
            field=models.CharField(blank=True, default='Rojo', max_length=255, null=True, verbose_name='Station status (Verde, Amarillo o Rojo. Otros quedarán en gris)'),
        ),
    ]
