# Generated by Django 4.0.4 on 2022-09-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagazapp', '0006_alter_lake_station_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lake',
            name='warning',
        ),
        migrations.AddField(
            model_name='lake',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lake',
            name='station_status',
            field=models.CharField(blank=True, default='Rojo', max_length=255, null=True, verbose_name="Station status (Debe empezar con 'Verde', 'Amarillo' o 'Rojo'. Otros quedarán en gris)"),
        ),
    ]
