# Generated by Django 4.0.4 on 2022-09-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagazapp', '0007_remove_lake_warning_lake_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
