# Generated by Django 4.0.4 on 2022-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagazapp', '0008_alter_lake_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='current_alert_status',
            field=models.CharField(blank=True, default='Verde', max_length=255, null=True, verbose_name="Current alert status (Debe empezar con 'Verde', 'Amarillo' o 'Rojo'. Otros quedarán en gris)"),
        ),
        migrations.AlterField(
            model_name='lake',
            name='station_status',
            field=models.CharField(blank=True, default='Instalación Programada', max_length=255, null=True, verbose_name="Station status (Debe empezar con 'Verde', 'Amarillo' o 'Rojo'. Otros quedarán en gris)"),
        ),
        migrations.AlterField(
            model_name='lakemeasurement',
            name='alert_status',
            field=models.CharField(blank=True, default='Verde (inicial)', max_length=255, null=True, verbose_name="Alert Status (Debe empezar con 'Verde', 'Amarillo' o 'Rojo'. Otros quedarán en gris)"),
        ),
    ]
