# Generated by Django 4.0.4 on 2023-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagazapp', '0009_lake_current_alert_status_alter_lake_station_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='station_status',
            field=models.CharField(blank=True, default='Instalación Programada', max_length=255, null=True, verbose_name='Station status (Ej: Operativa, Instalación Programada, Operativa sin Pluviómetro, etc)'),
        ),
    ]
