# Generated by Django 4.0.4 on 2023-06-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagazapp', '0010_alter_lake_station_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lakemeasurement',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='lake',
            name='last_data_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last data date'),
        ),
    ]
